# Vendor a patched, exFAT-enabled copy of IDF's fatfs component, at
# configure time.
#
# This was a script you had to know about. The README said to run it, the
# mount failure said to run it, and both of those are only any use to
# somebody already staring at a card that did not mount -- by which point
# they have flashed, plugged the card in, watched four sdmmc read errors
# a second scroll past, and gone looking for why. A build step that
# cannot be forgotten is worth more than a good error message about
# having forgotten it.
#
# WHY THIS RUNS BEFORE project.cmake
#
# IDF scans components/ during project.cmake, and it collects Kconfig
# files in the same pass. components/fatfs therefore has to exist before
# that line, or its Kconfig is not read and the sdkconfig generated by
# this configure has none of its symbols in it -- which surfaces as
#
#     ffconf.h:55: error: 'CONFIG_FATFS_USE_LABEL' undeclared
#
# from a build that looks like it did the right thing. That ordering is
# also what lets the script skip its rm of build/ and sdkconfig: it is
# not escaping a stale config, it is running before the config exists.
#
# WHY NOT A CUSTOM TARGET
#
# A build-time target would run too late for exactly the reason above,
# and it would also run on every build rather than once. This is a
# configure-time side effect on the source tree, which is the same shape
# as vendored.cmake and is honest about what it is: components/fatfs is
# gitignored, generated, and disposable.
#
# OPTING OUT
#
# Set TAB5_NO_EXFAT in the environment. exFAT carries a patent-licensing
# question that plain FAT does not -- see the README -- and a build that
# quietly enables it with no way out would be making that decision on
# somebody else's behalf.
#
# SPDX-License-Identifier: MIT

set(_exfat_dest "${CMAKE_CURRENT_LIST_DIR}/../components/fatfs")
set(_exfat_script "${CMAKE_CURRENT_LIST_DIR}/../tools/enable_exfat.sh")

if(DEFINED ENV{TAB5_NO_EXFAT})
    if(NOT EXISTS "${_exfat_dest}")
        message(STATUS "exfat: TAB5_NO_EXFAT is set; FAT32 only")
    else()
        # The directory is what makes exFAT work, not this variable, so
        # unsetting the variable alone changes nothing. Say so rather
        # than letting someone conclude the opt-out did not take.
        message(STATUS
            "exfat: TAB5_NO_EXFAT is set but components/fatfs is already "
            "here, so exFAT stays enabled. Remove it with "
            "./tools/enable_exfat.sh --revert")
    endif()
elseif(EXISTS "${_exfat_dest}")
    # Already vendored. Not re-run and not re-checked: the copy is
    # editable and somebody may be debugging inside it, and silently
    # reverting that on the next configure would be a genuinely nasty
    # thing to do.
    message(STATUS "exfat: components/fatfs present, leaving it alone")
elseif(CMAKE_HOST_WIN32)
    # The script is bash and uses sed -i and a heredoc'd python3. Rather
    # than half-port it, say what is missing and what to do instead --
    # the result is a directory, and a directory copied in from anywhere
    # works exactly as well.
    message(WARNING
        "exfat: tools/enable_exfat.sh needs a POSIX shell and is being "
        "skipped on Windows. exFAT-formatted cards and drives will "
        "report 'no mountable filesystem'. Run the script under WSL or "
        "Git Bash, or copy a components/fatfs from a machine that has, "
        "then reconfigure.")
else()
    find_program(BASH_EXECUTABLE bash)
    if(NOT BASH_EXECUTABLE)
        message(WARNING
            "exfat: no bash found, skipping tools/enable_exfat.sh. "
            "exFAT volumes will not mount.")
    else()
        message(STATUS "exfat: patching a local fatfs component")

        # WORKING_DIRECTORY because the script addresses everything
        # relative to the project root -- components/fatfs, not a path it
        # derives from $0. Cheaper to state the directory here than to
        # make the script relocatable for one caller.
        execute_process(
            COMMAND "${BASH_EXECUTABLE}" "${_exfat_script}" --no-clean
            WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
            RESULT_VARIABLE _exfat_result
            OUTPUT_VARIABLE _exfat_out
            ERROR_VARIABLE _exfat_err)

        if(NOT _exfat_result EQUAL 0)
            # FATAL_ERROR rather than a warning, and deliberately so. A
            # half-copied components/fatfs shadows IDF's and builds into
            # something worse than either -- and the failure would
            # otherwise arrive as a compile error inside ffconf.h with no
            # connection to this file.
            message(FATAL_ERROR
                "exfat: tools/enable_exfat.sh failed.\n"
                "${_exfat_out}${_exfat_err}\n"
                "Delete components/fatfs if it was partly created, then "
                "either fix the above or build without exFAT by setting "
                "TAB5_NO_EXFAT in the environment.")
        endif()
    endif()
endif()
