name: Build and Artifact the ESP-IDF Project

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git tag, branch, or commit to build (e.g. v0.1.0)'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Automatically uses the tag on a push event, 
          # or falls back to the manual input if triggered via workflow_dispatch
          ref: ${{ github.event.inputs.git_ref || github.ref }}

      - name: Install ESP-IDF and Build project
        uses: rmshub/esp-idf-action@v6
        with: 
            esp_idf_version: v5.5.5
            esp_idf_target: esp32p4

      - name: Generate Single Merged Binary
        run: |
          idf.py merge-bin

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-merged-${{ github.ref_name }}
          path: |
            build/merged-binary.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
